export const testPayload = {
  num_classes: 3,
  days: 5,
  slots_per_day: 6,
  total_rooms: 6,
  total_teachers: 8,
  subject_hours: { 0: 4, 1: 3, 2: 3 },
  subject_teachers: { 0: [0, 1], 1: [2, 3], 2: [4, 5] },
  class_names: ["CS-A1", "MATH-A1", "PHYS-A1"],
  subject_names: ["Computer Science", "Mathematics", "Physics"],
  teacher_names: [
    "John Smith",
    "Mary Johnson",
    "Robert Williams",
    "Sarah Brown",
    "Michael Jones",
    "Jennifer Davis",
    "David Miller",
    "Lisa Wilson",
  ],
  room_names: ["R101", "R102", "R103", "R104", "R105", "R106"],
  max_hours_per_day: 6,
  max_hours_per_week: 20,
  mutation_rate: 0.02,
  population_size: 60,
  generations: 80,
};
