const mockSchedule = [
  {
    day: "Monday",
    date: "Jan 15",
    classes: [
      {
        id: "1",
        subject: "Data Structures",
        teacher: "Dr. Smith",
        room: "Room 101",
        startTime: "9:00",
        endTime: "10:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
      {
        id: "2",
        subject: "Algorithm Lab",
        teacher: "Prof. Johnson",
        room: "Lab 201",
        startTime: "10:00",
        endTime: "12:00",
        type: "lab",
        color: "bg-accent border-destructive",
      },
      {
        id: "3",
        subject: "Database Systems",
        teacher: "Dr. Wilson",
        room: "Room 102",
        startTime: "2:00",
        endTime: "3:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
    ],
  },
  {
    day: "Tuesday",
    date: "Jan 16",
    classes: [
      {
        id: "4",
        subject: "Operating Systems",
        teacher: "Dr. Brown",
        room: "Room 103",
        startTime: "9:00",
        endTime: "10:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
      {
        id: "5",
        subject: "Computer Networks",
        teacher: "Prof. Davis",
        room: "Room 104",
        startTime: "11:00",
        endTime: "12:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
    ],
  },
  {
    day: "Wednesday",
    date: "Jan 17",
    classes: [
      {
        id: "6",
        subject: "Software Engineering",
        teacher: "Dr. Taylor",
        room: "Room 105",
        startTime: "10:00",
        endTime: "11:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
      {
        id: "7",
        subject: "Web Development Lab",
        teacher: "Prof. Anderson",
        room: "Lab 202",
        startTime: "1:00",
        endTime: "3:00",
        type: "lab",
        color: "bg-accent border-destructive",
      },
    ],
  },
  {
    day: "Thursday",
    date: "Jan 18",
    classes: [
      {
        id: "8",
        subject: "Machine Learning",
        teacher: "Dr. White",
        room: "Room 106",
        startTime: "9:00",
        endTime: "10:00",
        type: "lecture",
        color: "bg-accent border-primary",
      },
      {
        id: "9",
        subject: "AI Tutorial",
        teacher: "Prof. Miller",
        room: "Room 107",
        startTime: "3:00",
        endTime: "4:00",
        type: "tutorial",
        color: "bg-accent border-primary",
      },
    ],
  },
  {
    day: "Friday",
    date: "Jan 19",
    classes: [
      {
        id: "10",
        subject: "Project Work",
        teacher: "Dr. Garcia",
        room: "Lab 203",
        startTime: "10:00",
        endTime: "12:00",
        type: "lab",
        color: "bg-accent border-destructive",
      },
    ],
  },
];

export { mockSchedule };
